#!/bin/sh
#
# Start linuxptp
#

set -e -u -o pipefail

SLAVE_ETH="eno0"
PTP4L_CFG="/etc/ptp4l_default.cfg"
PTP4L_PIDFILE="/var/run/linuxptp-ptp4l.pid"
PHC2SYS_PIDFILE="/var/run/linuxptp-phc2sys.pid"

start() {
	printf "Starting linuxptp daemon: "
	start-stop-daemon -S -b -q -m -p "${PTP4L_PIDFILE}" \
		-x /usr/sbin/ptp4l -- -i "${SLAVE_ETH}" -s -f "${PTP4L_CFG}" \
		&& status=$? || status=$?
	[ ${status} = 0 ] && echo "OK" || echo "FAIL"

	printf "Starting linuxptp system clock synchronization: "
	start-stop-daemon -S -b -q -m -p "${PHC2SYS_PIDFILE}" \
		-x /usr/sbin/phc2sys -- -a -r && status=$? || status=$?
	[ ${status} = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping linuxptp system clock synchronization: "
	start-stop-daemon -K -q -p "${PHC2SYS_PIDFILE}" \
		-x /usr/sbin/phc2sys && status=$? || status=$?
	[ ${status} = 0 ] && echo "OK" || echo "FAIL"

	printf "Stopping linuxptp daemon: "
	start-stop-daemon -K -q -p "${PTP4L_PIDFILE}" \
		-x /usr/sbin/ptp4l && status=$? || status=$?
	[ ${status} = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
